### PR TITLE
Add CNCF svg to footer

### PR DESCRIPTION
**Pull request by skoech**
Signed-off-by: Sharon Koech <sharonkoech5147@gmail.com>

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
yay svg! nice change :)

**Comment by skoech** [comment]
Thanks. It's a little too big, though, right? :D
Let me try making it smaller.

**Comment by Licenser** [comment]
ja good call, it's a bit big, but still better then no logo :D

**Comment by skoech** [comment]
Very true. :D

**Pull request merged**
